# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: Cargo.lock
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
        exclude: \.rs$
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: name-tests-test
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace

  - repo: https://github.com/lovesegfault/beautysh
    rev: v6.2.1
    hooks:
      - id: beautysh

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args: ["--ignore-words-list", "crate"]
        exclude: Cargo.lock

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.19
    hooks:
      - id: mdformat

  - repo: https://github.com/AndrejOrsula/pre-commit-cargo
    rev: 0.3.0
    hooks:
      - id: cargo-fmt
      - id: cargo-update
      - id: cargo-clippy
        args: ["--workspace", "--all-targets", "--", "--deny=warnings"]
      - id: cargo-check
        args: ["--workspace", "--all-targets"]
      - id: cargo-test
        args: ["--workspace", "--all-targets"]
      - id: cargo-test-doc
        args: ["--workspace"]
      - id: cargo-doc
        args: ["--workspace", "--no-deps", "--document-private-items"]
      - id: cargo-deny-check
