[graph]
targets = [
    { triple = "aarch64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
]
all-features = true

# Considered when running `cargo deny check advisories`
# https://embarkstudios.github.io/cargo-deny/checks/advisories/cfg.html
[advisories]
ignore = []

# Considered when running `cargo deny check bans`
# https://embarkstudios.github.io/cargo-deny/checks/bans/cfg.html
[bans]
multiple-versions = "warn"
wildcards = "allow"
deny = []
skip = []
skip-tree = []

# Considered when running `cargo deny check licenses`
# https://embarkstudios.github.io/cargo-deny/checks/licenses/cfg.html
[licenses]
private = { ignore = true }
confidence-threshold = 0.9
allow = [
    "Apache-2.0 WITH LLVM-exception", # https://spdx.org/licenses/LLVM-exception.html
    "Apache-2.0",                     # https://spdx.org/licenses/Apache-2.0.html
    "MIT",                            # https://spdx.org/licenses/MIT.html
    "Unicode-3.0",                    # https://spdx.org/licenses/Unicode-3.0.html
]
exceptions = []
[[licenses.clarify]]
crate = "ring"
expression = "ISC"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

# Considered when running `cargo deny check sources`
# https://embarkstudios.github.io/cargo-deny/checks/sources/cfg.html
[sources]
unknown-registry = "deny"
unknown-git = "deny"
[sources.allow-org]
github = ["AndrejOrsula"]
